name: Generate Snake

on:
  schedule:
    - cron: "0 */24 * * *" # Jalankan setiap 24 jam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: RafliRizkya
          svg_out_path: github-contribution-grid-snake.svg  # Tanpa dist/

      - name: Create dist directory
        run: mkdir -p dist

      - name: Move SVG to dist
        run: mv github-contribution-grid-snake.svg dist/

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
