name: Generate Snake

on:
  schedule:
    - cron: "0 */24 * * *" # Jalankan setiap 24 jam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@v3.1.0  # Ganti dengan versi rilis tertentu (jika ada)
        id: snake-gif
        with:
          github_user_name: RafliRizkya
          svg_out_path: snake.svg  # Coba snake.svg

      - name: Check Output
        run: ls -l snake.svg  # Periksa apakah file SVG ada
