name: Generate Snake

on:
  schedule:
    - cron: "0 */24 * * *" # Jalankan setiap 24 jam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@v3  # Gunakan versi rilis (contoh)
        id: snake-gif
        with:
          github_user_name: RafliRizkya
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Check Output
        run: ls -l dist/github-contribution-grid-snake.svg  # Periksa apakah file SVG ada

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3 # Gunakan versi rilis
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
